version: '3.8'

services:
  fastapi:
    build: .
    environment:
      - APP_NAME=${APP_NAME}
      - VERSION=${VERSION}
      ######
      ## Custom Env Vars Below
      ######
    ports:
      - "8000:8000"
    volumes:
      - .:/svc
    command: pipenv run uvicorn scripts.main:app --host 0.0.0.0 --port 8000 --reload
