@default:
    just --list

######
## ODLC Root setup block
######

[macos]
setup:
    echo "Add mac installation scripts here."

[linux]
setup:
    #!/usr/bin/env bash
    set -euxo pipefail

    #####
    ### This script is debian-oriented.  TODO: more distros
    #####
    sudo apt-get install apt-transport-https ca-certificates gnupg

    #####
    ### docker local dev setup
    #####
    if ! command -v docker &> /dev/null
    then
        curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
        sudo sh /tmp/get-docker.sh
        sudo groupadd docker
        sudo usermod -aG docker $USER
    else
        echo "Docker installed"
    fi


    #####
    ### gcloud local dev setup
    #####
    if ! command -v gcloud &> /dev/null
    then
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
        sudo apt-get update && sudo apt-get install google-cloud-cli
        gcloud init
        gcloud auth application-default login
        gcloud auth configure-docker
    else
        echo "gcloud installed"
    fi


    #####
    ### Terraform local dev setup
    #####
    if ! command -v terraform &> /dev/null
    then
        wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt update
        sudo apt-get install terraform
    else
        echo "terraform installed"
    fi
