name: Image Register
on:
  push:
    branches:
      - main
    paths:
      - 'images/**'
jobs:
  image-register:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/iomorphic/dev-image:latest
      volumes:
        - /usr/bin/docker:/usr/bin/docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '2'

      - name: Authenticate via service-account with Google Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: {{ cookiecutter.gar_container_dns }}
          username: _json_key_base64
          {% raw %}password: ${{ secrets.GAR_JSONKEY_B64 }}{% endraw %}

      - name: Authenticate to dockerhub
        uses: docker/login-action@v2
        with:
          username: {{ cookiecutter.root_name }}
          {% raw %}password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Authenticate via github actions token
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}{% endraw %}

      # Needed due to: https://github.com/actions/checkout/issues/766
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - env:
          GHCR_REGISTRY_URL: ghcr.io/{{cookiecutter.root_name}}
          GAR_REGISTRY_URL: {{cookiecutter.gar_container_dns}}/{{cookiecutter.root_name}}/images
          DH_REGISTRY_URL: {{cookiecutter.root_name}}
        run: just register images
