name: Package PR
on:
  pull_request:
    paths:
      - 'packages/**'
jobs:
  package-pr:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/iomorphic/dev-py:latest
      volumes:
        - /usr/bin/docker:/usr/bin/docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      # Needed due to: https://github.com/actions/checkout/issues/766
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - env:
          GAR_PYPI_USERNAME: _json_key_base64
          {% raw %}GAR_PYPI_PASSWORD: ${{ secrets.GAR_JSONKEY_B64 }}{% endraw %}
        run: just pr packages
