name: Package Register
on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
jobs:
  package-register:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/iomorphic/dev-py:latest
      volumes:
        - /usr/bin/docker:/usr/bin/docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '2'

      # Needed due to: https://github.com/actions/checkout/issues/766
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - env:
          GAR_PYPI_URL: {{ cookiecutter.gar_pypi_url }}
          GAR_PYPI_USERNAME: _json_key_base64
          {% raw %}GAR_PYPI_PASSWORD: ${{ secrets.GAR_JSONKEY_B64 }}{% endraw %}
        run: just register packages
