name: Service Register
on:
  push:
    branches:
      - main
    paths:
      - 'services/**'
env:
  GOOGLE_APPLICATION_CREDENTIALS: '/tmp/gac.json'
jobs:
  service-register:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/iomorphic/dev-image:latest
      volumes:
        - /usr/bin/docker:/usr/bin/docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '2'

      # Needed for keyring support
      - run: {% raw %}echo ${{ secrets.GAR_JSONKEY_B64 }} | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS{% endraw %}

      - name: Authenticate via service-account with Google Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: {{ cookiecutter.gar_container_dns }}
          username: _json_key_base64
          {% raw %}password: ${{ secrets.GAR_JSONKEY_B64 }}{% endraw %}

      # Needed due to: https://github.com/actions/checkout/issues/766
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - env:
          GAR_REGISTRY_URL: {{cookiecutter.gar_container_dns}}/{{cookiecutter.root_name}}/services
        run: just register services

