name: Service PR
on:
  pull_request:
    paths:
      - 'services/**'
env:
  GOOGLE_APPLICATION_CREDENTIALS: '/tmp/gac.json'
jobs:
  service-pr:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/iomorphic/dev-py:latest
      volumes:
        - /usr/bin/docker:/usr/bin/docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      # Needed for keyring support
      - run: {% raw %}echo ${{ secrets.GAR_JSONKEY_B64 }} | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS{% endraw %}

      # Needed due to: https://github.com/actions/checkout/issues/766
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - run: just pr services
