name: Image Register
on:
  push:
    branches:
      - main
    paths:
      - 'images/**'
jobs:
  image-register:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/iomorphic/dev-image:latest
      volumes:
        - /usr/bin/docker:/usr/bin/docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '2'

{% raw %}
      - name: Authenticate via service-account with Google Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: us-west1-docker.pkg.dev
          username: _json_key_base64
          password: ${{ secrets.PRIVATE_REGISTRY_JSONKEY_B64 }}

      - name: Authenticate via github actions token
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
{% endraw %}

      # Needed due to: https://github.com/actions/checkout/issues/766
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - run: just register images
