name: Infra PR
on:
  pull_request:
    paths:
      - 'infra/**'
jobs:
  infra-pr:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    container:
      image: {{cookiecutter.image_repo_url}}/dev-infra:latest
      volumes:
        - /usr/bin/docker:/usr/bin/docker
      credentials:
        username: _json_key_base64
        password: {{cookiecutter.secret_payload}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Authenticate via service-account with Google Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: us-west1-docker.pkg.dev
          username: _json_key_base64
          password: {{cookiecutter.secret_payload}}

      # Needed due to: https://github.com/actions/checkout/issues/766
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - run: just infra_pr
