PRIVATE_REGISTRY_URL:='{{cookiecutter.registry_dns}}/{{cookiecutter.registry_path}}'
IMAGE_NAME:='{{cookiecutter.project_name}}'
DEV_IMAGE:='ghcr.io/iomorphic/dev-image:latest'
VERSION:='0.0.1'
GIT_SHORTHASH:=`git rev-parse --short HEAD`

######
## ODLC Section
######

@default:
    just --list

@verify: lint typecheck test

@pr: verify
    echo "PR is successful!"

{% raw %}
@build:
    docker build -t {{IMAGE_NAME}}_local .

@register:
    docker tag {{IMAGE_NAME}}_local {{PRIVATE_REGISTRY_URL}}/{{IMAGE_NAME}}:latest
    docker tag {{IMAGE_NAME}}_local {{PRIVATE_REGISTRY_URL}}/{{IMAGE_NAME}}:{{VERSION}}
    docker tag {{IMAGE_NAME}}_local {{PRIVATE_REGISTRY_URL}}/{{IMAGE_NAME}}:{{GIT_SHORTHASH}}
    docker image push --all-tags {{PRIVATE_REGISTRY_URL}}/{{IMAGE_NAME}}

######
## CodeDLC Section
######

@init:
    echo "Init not supported for images"

@docker SUBCOMMAND:
    docker  run  -v `pwd`:`pwd` -w `pwd` -i -t {{DEV_IMAGE}} just {{SUBCOMMAND}}
{% endraw %}

@lint:
    hadolint Dockerfile

@typecheck:
    echo "Typecheck not supported for images"

@test:
    echo "Unit testing not supported for images"

@format:
    echo "Re-format not supported for images"


######
## ImageDLC Section
######

{% raw %}
@bash: build
    @docker run --rm -it {{IMAGE_NAME}}_local /bin/bash
{% endraw %}
