name: Register
on:
  push:
    branches:
      - main
jobs:
  register:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/iomorphic/dev-py:latest
      volumes:
        - /usr/bin/docker:/usr/bin/docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '2'

      - env:
          PYPI_USERNAME: __token__
          {% raw %}PYPI_PASSWORD: ${{ secrets.PYPI_REGISTRY_KEY }}{% endraw %}
        run: just register
