PROJECT_NAME:='{{cookiecutter.project_name}}'
DEV_IMAGE:='ghcr.io/iomorphic/dev-py:latest'
SRC_FOLDER:='src'
TEST_FOLDER:='tests'


{% raw %}
@default:
    just --list

@verify: lint typecheck test
    echo "Done with Verification"

@pr: init verify
    echo "PR is successful!"

@init:
    [ -f Pipfile.lock ] && echo "Lockfile already exists" || PIPENV_VENV_IN_PROJECT=1 pipenv lock
    PIPENV_VENV_IN_PROJECT=1 pipenv sync --dev

# docker host-mapped venv cannot be shared for localdev; container modified files not remapped to host user; pipenv sync is slow for subsequent cmds
@docker SUBCOMMAND FORCE="noforce":
    #!/usr/bin/env bash
    if [ "{{FORCE}}" = "--force" ]  || [ "{{FORCE}}" = "-f" ]; then
        docker container prune --force
        docker volume rm --force {{PROJECT_NAME}}_pyvenv
    fi
    docker run -i -v `pwd`:`pwd` -v {{PROJECT_NAME}}_pyvenv:`pwd`/.venv -w `pwd` {{DEV_IMAGE}} just init {{SUBCOMMAND}}

@lint:
    pipenv run ruff check {{SRC_FOLDER}} {{TEST_FOLDER}}

@typecheck:
    pipenv run mypy --explicit-package-bases -p {{PROJECT_NAME}}
    pipenv run mypy --allow-untyped-defs tests

@test:
    pipenv run pytest --hypothesis-show-statistics {{TEST_FOLDER}}

@format:
    pipenv run ruff check --fix {{SRC_FOLDER}} {{TEST_FOLDER}}
    pipenv run black --verbose {{SRC_FOLDER}} {{TEST_FOLDER}}
{% endraw %}
######
## Custom Section
######
