DEV_IMAGE:='ghcr.io/iomorphic/dev-infra:latest'

{% raw %}
######
## ODLC Section
######

@default:
    just --list

@verify: lint typecheck test

@pr: init verify
    echo "PR is successful!"

@build:
    echo "We are executing terraform from laptops so no op needed here."

@register: build
    echo "We are executing terraform from laptops so no op needed here."

######
## CodeDLC Section
######

@init:
    terraform init

@docker SUBCOMMAND:
    docker run -i -v "$HOME/.config/gcloud/application_default_credentials.json":/gcp/adc.json:ro --env GOOGLE_APPLICATION_CREDENTIALS=/gcp/adc.json -v `pwd`:`pwd` -w `pwd` {{DEV_IMAGE}} just {{SUBCOMMAND}}

@lint:
    terraform fmt -check

@typecheck:
    terraform validate

@test:
    echo "Unit testing not supported for terraform"

@format:
    terraform fmt
{% endraw %}
